#!/bin/bash

#	Get wp-config values: $WP_path, $WP_conf, $WP_db, $WP_user, $WP_pass, $redisPw
	source ~/drWPscripts/getWPconfig.sh

#	Check if /archive directory exists
if [ ! -d /archive ] ; then

#	Create dir for scripts
	mkdir /archive
fi

#	Change dir
	cd /archive

#	Dump WP db into archive dir
	mysqldump -u $WP_user -p$WP_pass $WP_db > /archive/$dateHost.sql 2>/dev/null

#	Archive WP files into archive dir
	tar czf /archive/$dateHost.tgz $WP_path 2>/dev/null

#	Remove versions older than 10 days
	find . -maxdepth 1 -type f -mtime +10 -exec rm "{}" \;
